name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'CourtSpotter.API/**'
      - 'CourtSpotter.Core/**'
      - 'CourtSpotter.Infrastructure/**'
      - 'CourtSpotter.Infrastructure.Tests/**'
      - '*.sln'
      - '**/*.csproj'
  pull_request: 
    branches: [ main ]
    paths:
      - 'CourtSpotter.API/**'
      - 'CourtSpotter.Core/**'
      - 'CourtSpotter.Infrastructure/**'
      - 'CourtSpotter.Infrastructure.Tests/**'
      - '*.sln'
      - '**/*.csproj'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          
      - name: Restore dependencies
        run: dotnet restore CourtSpotter.sln

      - name: Build solution
        run: dotnet build CourtSpotter.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test CourtSpotter.sln --no-build --configuration Release --verbosity normal

  