name: Build and deploy ASP.Net Core app to Azure Web App - api-padelcourtsearch

on:
  push:
    branches:
      - main
    paths:
      - 'PadelCourts.API/**'
      - 'PadelCourts.Core/**'
      - 'PadelCourts.Infrastructure/**'
      - '*.sln'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore WebApplication1.sln

      - name: Build solution
        run: dotnet build WebApplication1.sln --configuration Release --no-restore

      - name: Publish API project
        run: dotnet publish PadelCourts.API/PadelCourts.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production  # This allows you to set environment-specific secrets

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-padelcourtsearch'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.__publishingprofilesecretname__ }}
